import {
  LucideArrowBigLeft,
  LucideBell,
  LucideClock,
  LucideDownload,
  LucideEllipsis,
  LucideHeart,
  LucideHouse,
  LucideInfo,
  LucideLibraryBig,
  LucideListMusic,
  LucideLock,
  LucideMail,
  LucidePause,
  LucidePlay,
  LucideRefreshCcw,
  LucideRepeat,
  LucideRepeat1,
  LucideSearch,
  LucideSettings,
  LucideShuffle,
  LucideSkipBack,
  LucideSkipForward,
  LucideUser,
  LucideVolume1,
  LucideVolume2,
  LucideVolumeX,
  LucideX,
} from '@lucide/angular';
import { IconConfig } from '@shared/interfaces/icon-config';

export const ICONS = {
  arrowBigLeft: { icon: LucideArrowBigLeft, label: 'Back' },
  bell: { icon: LucideBell, label: 'Notifications' },
  clock: { icon: LucideClock, label: 'Duration' },
  close: { icon: LucideX, label: 'Close' },
  download: { icon: LucideDownload, label: 'Download' },
  heart: { icon: LucideHeart, label: 'Add to favorites' },
  house: { icon: LucideHouse, label: 'Home' },
  info: { icon: LucideInfo, label: 'About' },
  library: { icon: LucideLibraryBig, label: 'Library List' },
  lock: { icon: LucideLock, label: 'Password' },
  mail: { icon: LucideMail, label: 'Email' },
  moreOptions: { icon: LucideEllipsis, label: 'More options' },
  nextTrack: { icon: LucideSkipForward, label: 'Next track' },
  pause: { icon: LucidePause, label: 'Pause' },
  play: { icon: LucidePlay, label: 'Play' },
  playlist: { icon: LucideListMusic, label: 'Playlist' },
  previousTrack: { icon: LucideSkipBack, label: 'Previous track' },
  repeat: { icon: LucideRepeat, label: 'Repeat' },
  repeatOne: { icon: LucideRepeat1, label: 'Repeat current track' },
  retry: { icon: LucideRefreshCcw, label: 'Retry' },
  search: { icon: LucideSearch, label: 'Search' },
  settings: { icon: LucideSettings, label: 'Settings' },
  shuffle: { icon: LucideShuffle, label: 'Shuffle' },
  user: { icon: LucideUser, label: 'Profile' },
  volumeDown: { icon: LucideVolume1, label: 'Volume down' },
  volumeOff: { icon: LucideVolumeX, label: 'Volume off' },
  volumeUp: { icon: LucideVolume2, label: 'Volume up' },
} as const satisfies Record<string, IconConfig>;

export type IconKey = keyof typeof ICONS;
