import {
  LucideArrowBigLeft,
  LucideBell,
  LucideClock,
  LucideDisc3,
  LucideDownload,
  LucideEllipsis,
  LucideHandMetal,
  LucideHeart,
  LucideHouse,
  LucideInfo,
  LucideLibraryBig,
  LucideListMusic,
  LucideLock,
  LucideMail,
  LucideMicVocal,
  LucidePause,
  LucidePlay,
  LucideRefreshCcw,
  LucideRepeat,
  LucideRepeat1,
  LucideSearch,
  LucideSettings,
  LucideShuffle,
  LucideSkipBack,
  LucideSkipForward,
  LucideUser,
  LucideUserPen,
  LucideVolume1,
  LucideVolume2,
  LucideVolumeX,
  LucideX,
  LucideMusic,
  LucideZap,
  LucideGuitar,
  LucidePiano,
  LucideKeyboardMusic,
  LucideDrum,
  LucideCrown,
  LucideMegaphone,
  LucideExternalLink,
} from '@lucide/angular';
import { IconConfig } from '@shared/interfaces/icon-config';

export const ICONS = {
  arrowBigLeft: { icon: LucideArrowBigLeft, label: 'Back' },
  bell: { icon: LucideBell, label: 'Notifications' },
  clock: { icon: LucideClock, label: 'Duration' },
  close: { icon: LucideX, label: 'Close' },
  download: { icon: LucideDownload, label: 'Download' },
  heart: { icon: LucideHeart, label: 'Add to favorites' },
  house: { icon: LucideHouse, label: 'Home' },
  info: { icon: LucideInfo, label: 'About' },
  library: { icon: LucideLibraryBig, label: 'Library List' },
  lock: { icon: LucideLock, label: 'Password' },
  mail: { icon: LucideMail, label: 'Email' },
  moreOptions: { icon: LucideEllipsis, label: 'More options' },
  nextTrack: { icon: LucideSkipForward, label: 'Next track' },
  pause: { icon: LucidePause, label: 'Pause' },
  play: { icon: LucidePlay, label: 'Play' },
  playlist: { icon: LucideListMusic, label: 'Playlist' },
  previousTrack: { icon: LucideSkipBack, label: 'Previous track' },
  repeat: { icon: LucideRepeat, label: 'Repeat' },
  repeatOne: { icon: LucideRepeat1, label: 'Repeat current track' },
  retry: { icon: LucideRefreshCcw, label: 'Retry' },
  search: { icon: LucideSearch, label: 'Search' },
  settings: { icon: LucideSettings, label: 'Settings' },
  shuffle: { icon: LucideShuffle, label: 'Shuffle' },
  user: { icon: LucideUser, label: 'User Name' },
  userPen: { icon: LucideUserPen, label: 'User Nickname' },
  volumeDown: { icon: LucideVolume1, label: 'Volume down' },
  volumeOff: { icon: LucideVolumeX, label: 'Volume off' },
  volumeUp: { icon: LucideVolume2, label: 'Volume up' },
  rock: { icon: LucideHandMetal, label: 'Rock' },
  electronic: { icon: LucideZap, label: 'Electronic' },
  classical: { icon: LucidePiano, label: 'Classical' },
  ambientNewAge: { icon: LucideDrum, label: 'Ambient/New Age' },
  filmscore: { icon: LucideKeyboardMusic, label: 'Filmscore' },
  advertising: { icon: LucideMegaphone, label: 'Advertising' },
  pop: { icon: LucideDisc3, label: 'Pop' },
  corporate: { icon: LucideCrown, label: 'Corporate' },
  alternative: { icon: LucideGuitar, label: 'Alternative' },
  music: { icon: LucideMusic, label: 'Music' },
  albums: { icon: LucideDisc3, label: 'Albums' },
  artists: { icon: LucideMicVocal, label: 'Artists' },
  expand: { icon: LucideExternalLink, label: 'Expand' },
} as const satisfies Record<string, IconConfig>;

export type IconKey = keyof typeof ICONS;
